from . import AbstractListener as AbstractListener
from .xorg_keysyms import SYMBOLS as SYMBOLS
from collections.abc import Generator
from typing import Any

class X11Error(Exception): ...

def display_manager(display) -> Generator[Any, None, None]: ...
def alt_mask(display): ...
def alt_gr_mask(display): ...
def numlock_mask(display): ...
def keysym_is_latin_upper(keysym): ...
def keysym_is_latin_lower(keysym): ...
def keysym_group(ks1, ks2): ...
def keysym_normalize(keysym): ...
def index_to_shift(display, index): ...
def shift_to_index(display, shift): ...
def keyboard_mapping(display): ...
def char_to_keysym(char): ...
def symbol_to_keysym(symbol): ...

class ListenerMixin: ...
