
# mapping HTML entities to plain characters

# note this isn't strictly correct.  For my needs I don't distinguish
# between en dash, em dash and hyphen.

_entities = {
    '&#145;': "`",
    '&#146;': "'",
    '&#149;': "*",
    '&#150;': '-',
    '&#151;': '-',
    '&#160;': ' ',
    '&#161;': u"\N{INVERTED EXCLAMATION MARK}",
    '&#162;': u"\N{CENT SIGN}",
    '&#163;': u"\N{POUND SIGN}",
    '&#164;': u"\N{CURRENCY SIGN}",
    '&#165;': u"\N{YEN SIGN}",
    '&#166;': u"\N{BROKEN BAR}",
    '&#167;': u"\N{SECTION SIGN}",
    '&#168;': u"\N{DIAERESIS}",
    '&#169;': u"\N{COPYRIGHT SIGN}",
    '&#170;': u"\N{FEMININE ORDINAL INDICATOR}",
    '&#171;': u"\N{LEFT-POINTING DOUBLE ANGLE QUOTATION MARK}",
    '&#172;': u"\N{NOT SIGN}",
    '&#173;': u"\N{SOFT HYPHEN}",
    '&#174;': u"\N{REGISTERED SIGN}",
    '&#175;': u"\N{MACRON}",
    '&#176;': u"\N{DEGREE SIGN}",
    '&#177;': u"\N{PLUS-MINUS SIGN}",
    '&#178;': u"\N{SUPERSCRIPT TWO}",
    '&#179;': u"\N{SUPERSCRIPT THREE}",
    '&#180;': u"\N{ACUTE ACCENT}",
    '&#181;': u"\N{MICRO SIGN}",
    '&#182;': u"\N{PILCROW SIGN}",
    '&#183;': u"\N{MIDDLE DOT}",
    '&#184;': u"\N{CEDILLA}",
    '&#185;': u"\N{SUPERSCRIPT ONE}",
    '&#186;': u"\N{MASCULINE ORDINAL INDICATOR}",
    '&#187;': u"\N{RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK}",
    '&#188;': u"\N{VULGAR FRACTION ONE QUARTER}",
    '&#189;': u"\N{VULGAR FRACTION ONE HALF}",
    '&#190;': u"\N{VULGAR FRACTION THREE QUARTERS}",
    '&#191;': u"\N{INVERTED QUESTION MARK}",
    '&#192;': u"\N{LATIN CAPITAL LETTER A WITH GRAVE}",
    '&#193;': u"\N{LATIN CAPITAL LETTER A WITH ACUTE}",
    '&#194;': u"\N{LATIN CAPITAL LETTER A WITH CIRCUMFLEX}",
    '&#195;': u"\N{LATIN CAPITAL LETTER A WITH TILDE}",
    '&#196;': u"\N{LATIN CAPITAL LETTER A WITH DIAERESIS}",
    '&#197;': u"\N{LATIN CAPITAL LETTER A WITH RING ABOVE}",
    '&#198;': u"\N{LATIN CAPITAL LETTER AE}",
    '&#199;': u"\N{LATIN CAPITAL LETTER C WITH CEDILLA}",
    '&#200;': u"\N{LATIN CAPITAL LETTER E WITH GRAVE}",
    '&#201;': u"\N{LATIN CAPITAL LETTER E WITH ACUTE}",
    '&#202;': u"\N{LATIN CAPITAL LETTER E WITH CIRCUMFLEX}",
    '&#203;': u"\N{LATIN CAPITAL LETTER E WITH DIAERESIS}",
    '&#204;': u"\N{LATIN CAPITAL LETTER I WITH GRAVE}",
    '&#205;': u"\N{LATIN CAPITAL LETTER I WITH ACUTE}",
    '&#206;': u"\N{LATIN CAPITAL LETTER I WITH CIRCUMFLEX}",
    '&#207;': u"\N{LATIN CAPITAL LETTER I WITH DIAERESIS}",
    '&#208;': u"\N{LATIN CAPITAL LETTER ETH}",
    '&#209;': u"\N{LATIN CAPITAL LETTER N WITH TILDE}",
    '&#210;': u"\N{LATIN CAPITAL LETTER O WITH GRAVE}",
    '&#211;': u"\N{LATIN CAPITAL LETTER O WITH ACUTE}",
    '&#212;': u"\N{LATIN CAPITAL LETTER O WITH CIRCUMFLEX}",
    '&#213;': u"\N{LATIN CAPITAL LETTER O WITH TILDE}",
    '&#214;': u"\N{LATIN CAPITAL LETTER O WITH DIAERESIS}",
    '&#215;': u"\N{MULTIPLICATION SIGN}",
    '&#216;': u"\N{LATIN CAPITAL LETTER O WITH STROKE}",
    '&#217;': u"\N{LATIN CAPITAL LETTER U WITH GRAVE}",
    '&#218;': u"\N{LATIN CAPITAL LETTER U WITH ACUTE}",
    '&#219;': u"\N{LATIN CAPITAL LETTER U WITH CIRCUMFLEX}",
    '&#220;': u"\N{LATIN CAPITAL LETTER U WITH DIAERESIS}",
    '&#221;': u"\N{LATIN CAPITAL LETTER Y WITH ACUTE}",
    '&#222;': u"\N{LATIN CAPITAL LETTER THORN}",
    '&#223;': u"\N{LATIN SMALL LETTER SHARP S}",
    '&#224;': u"\N{LATIN SMALL LETTER A WITH GRAVE}",
    '&#225;': u"\N{LATIN SMALL LETTER A WITH ACUTE}",
    '&#226;': u"\N{LATIN SMALL LETTER A WITH CIRCUMFLEX}",
    '&#227;': u"\N{LATIN SMALL LETTER A WITH TILDE}",
    '&#228;': u"\N{LATIN SMALL LETTER A WITH DIAERESIS}",
    '&#229;': u"\N{LATIN SMALL LETTER A WITH RING ABOVE}",
    '&#230;': u"\N{LATIN SMALL LETTER AE}",
    '&#231;': u"\N{LATIN SMALL LETTER C WITH CEDILLA}",
    '&#232;': u"\N{LATIN SMALL LETTER E WITH GRAVE}",
    '&#233;': u"\N{LATIN SMALL LETTER E WITH ACUTE}",
    '&#234;': u"\N{LATIN SMALL LETTER E WITH CIRCUMFLEX}",
    '&#235;': u"\N{LATIN SMALL LETTER E WITH DIAERESIS}",
    '&#236;': u"\N{LATIN SMALL LETTER I WITH GRAVE}",
    '&#237;': u"\N{LATIN SMALL LETTER I WITH ACUTE}",
    '&#238;': u"\N{LATIN SMALL LETTER I WITH CIRCUMFLEX}",
    '&#239;': u"\N{LATIN SMALL LETTER I WITH DIAERESIS}",
    '&#240;': u"\N{LATIN SMALL LETTER ETH}",
    '&#241;': u"\N{LATIN SMALL LETTER N WITH TILDE}",
    '&#242;': u"\N{LATIN SMALL LETTER O WITH GRAVE}",
    '&#243;': u"\N{LATIN SMALL LETTER O WITH ACUTE}",
    '&#244;': u"\N{LATIN SMALL LETTER O WITH CIRCUMFLEX}",
    '&#245;': u"\N{LATIN SMALL LETTER O WITH TILDE}",
    '&#246;': u"\N{LATIN SMALL LETTER O WITH DIAERESIS}",
    '&#246;': u"\N{LATIN SMALL LETTER O WITH DIAERESIS}",
    '&#247;': u"\N{DIVISION SIGN}",
    '&#248;': u"\N{LATIN SMALL LETTER O WITH STROKE}",
    '&#249;': u"\N{LATIN SMALL LETTER U WITH GRAVE}",
    '&#250;': u"\N{LATIN SMALL LETTER U WITH ACUTE}",
    '&#251;': u"\N{LATIN SMALL LETTER U WITH CIRCUMFLEX}",
    '&#252;': u"\N{LATIN SMALL LETTER U WITH DIAERESIS}",
    '&#253;': u"\N{LATIN SMALL LETTER Y WITH ACUTE}",
    '&#254;': u"\N{LATIN SMALL LETTER THORN}",
    '&#255;': u"\N{LATIN SMALL LETTER Y WITH DIAERESIS}",
    '&#338;': u"\N{LATIN CAPITAL LIGATURE OE}",
    '&#339;': u"\N{LATIN SMALL LIGATURE OE}",
    '&#34;': '"',
    '&#352;': u"\N{LATIN CAPITAL LETTER S WITH CARON}",
    '&#353;': u"\N{LATIN SMALL LETTER S WITH CARON}",
    '&#376;': u"\N{LATIN CAPITAL LETTER Y WITH DIAERESIS}",
    '&#38;': "&",
    '&#39;': "'",
    '&#402;': u"\N{LATIN SMALL LETTER F WITH HOOK}",
    '&#60;': "<",
    '&#62;': ">",
    '&#64;': "@",
    '&#710;': u"\N{MODIFIER LETTER CIRCUMFLEX ACCENT}",
    '&#732;': u"\N{SMALL TILDE}",
    '&#8194;': u"\N{EN SPACE}",
    '&#8195;': u"\N{EM SPACE}",
    '&#8201;': u"\N{THIN SPACE}",
    '&#8204;': u"\N{ZERO WIDTH NON-JOINER}",
    '&#8205;': u"\N{ZERO WIDTH JOINER}",
    '&#8206;': u"\N{LEFT-TO-RIGHT MARK}",
    '&#8207;': u"\N{RIGHT-TO-LEFT MARK}",
    '&#8211;': "-",
    '&#8212;': "-",
    '&#8216;': u"\N{LEFT SINGLE QUOTATION MARK}",
    '&#8217;': "'",
    '&#8218;': u"\N{SINGLE LOW-9 QUOTATION MARK}",
    '&#8221;': '"',
    '&#8222;': u"\N{DOUBLE LOW-9 QUOTATION MARK}",
    '&#8224;': u"\N{DAGGER}",
    '&#8225;': u"\N{DOUBLE DAGGER}",
    '&#8226;': u"\N{BULLET}",
    '&#8240;': u"\N{PER MILLE SIGN}",
    '&#8249;': u"\N{SINGLE LEFT-POINTING ANGLE QUOTATION MARK}",
    '&#8250;': u"\N{SINGLE RIGHT-POINTING ANGLE QUOTATION MARK}",
    '&#8364;': u"\N{EURO SIGN}",
    '&Aacute;': u"\N{LATIN CAPITAL LETTER A WITH ACUTE}",
    '&aacute;': u"\N{LATIN SMALL LETTER A WITH ACUTE}",
    '&Acirc;': u"\N{LATIN CAPITAL LETTER A WITH CIRCUMFLEX}",
    '&acirc;': u"\N{LATIN SMALL LETTER A WITH CIRCUMFLEX}",
    '&acute;': u"\N{ACUTE ACCENT}",
    '&AElig;': u"\N{LATIN CAPITAL LETTER AE}",
    '&aelig;': u"\N{LATIN SMALL LETTER AE}",
    '&Agrave;': u"\N{LATIN CAPITAL LETTER A WITH GRAVE}",
    '&agrave;': u"\N{LATIN SMALL LETTER A WITH GRAVE}",
    '&alefsym;': u"\N{ALEF SYMBOL}",
    '&Alpha;': u"\N{GREEK CAPITAL LETTER ALPHA}",
    '&alpha;': u"\N{GREEK SMALL LETTER ALPHA}",
    '&amp;': '&',
    '&AMP;': '&',
    '&Amp;': '&',
    '&and;': u"\N{LOGICAL AND}",
    '&ang;': u"\N{ANGLE}",
    '&Aring;': u"\N{LATIN CAPITAL LETTER A WITH RING ABOVE}",
    '&aring;': u"\N{LATIN SMALL LETTER A WITH RING ABOVE}",
    '&asymp;': u"\N{ALMOST EQUAL TO}",
    '&Atilde;': u"\N{LATIN CAPITAL LETTER A WITH TILDE}",
    '&atilde;': u"\N{LATIN SMALL LETTER A WITH TILDE}",
    '&Auml;': u"\N{LATIN CAPITAL LETTER A WITH DIAERESIS}",
    '&auml;': u"\N{LATIN SMALL LETTER A WITH DIAERESIS}",
    '&bdquo;': u"\N{DOUBLE LOW-9 QUOTATION MARK}",
    '&Beta;': u"\N{GREEK CAPITAL LETTER BETA}",
    '&beta;': u"\N{GREEK SMALL LETTER BETA}",
    '&brvbar;': u"\N{BROKEN BAR}",
    '&bull;': u"\N{BULLET}",
    '&cap;': u"\N{INTERSECTION}",
    '&Ccedil;': u"\N{LATIN CAPITAL LETTER C WITH CEDILLA}",
    '&ccedil;': u"\N{LATIN SMALL LETTER C WITH CEDILLA}",
    '&cedil;': u"\N{CEDILLA}",
    '&cent;': u"\N{CENT SIGN}",
    '&Chi;': u"\N{GREEK CAPITAL LETTER CHI}",
    '&chi;': u"\N{GREEK SMALL LETTER CHI}",
    '&circ;': u"\N{MODIFIER LETTER CIRCUMFLEX ACCENT}",
    '&clubs;': u"\N{BLACK CLUB SUIT}",
    '&cong;': u"\N{APPROXIMATELY EQUAL TO}",
    '&copy;': u"\N{COPYRIGHT SIGN}",
    '&crarr;': u"\N{DOWNWARDS ARROW WITH CORNER LEFTWARDS}",
    '&cup;': u"\N{UNION}",
    '&curren;': u"\N{CURRENCY SIGN}",
    '&dagger;': u"\N{DAGGER}",
    '&Dagger;': u"\N{DOUBLE DAGGER}",
    '&darr;': u"\N{DOWNWARDS ARROW}",
    '&dArr;': u"\N{DOWNWARDS DOUBLE ARROW}",
    '&deg;': u"\N{DEGREE SIGN}",
    '&Delta;': u"\N{GREEK CAPITAL LETTER DELTA}",
    '&delta;': u"\N{GREEK SMALL LETTER DELTA}",
    '&diams;': u"\N{BLACK DIAMOND SUIT}",
    '&divide;': u"\N{DIVISION SIGN}",
    '&Eacute;': u"\N{LATIN CAPITAL LETTER E WITH ACUTE}",
    '&eacute;': u"\N{LATIN SMALL LETTER E WITH ACUTE}",
    '&Ecirc;': u"\N{LATIN CAPITAL LETTER E WITH CIRCUMFLEX}",
    '&ecirc;': u"\N{LATIN SMALL LETTER E WITH CIRCUMFLEX}",
    '&Egrave;': u"\N{LATIN CAPITAL LETTER E WITH GRAVE}",
    '&egrave;': u"\N{LATIN SMALL LETTER E WITH GRAVE}",
    '&empty;': u"\N{EMPTY SET}",
    '&emsp;': " ",
    '&ensp;': " ",
    '&Epsilon;': u"\N{GREEK CAPITAL LETTER EPSILON}",
    '&epsilon;': u"\N{GREEK SMALL LETTER EPSILON}",
    '&equiv;': u"\N{IDENTICAL TO}",
    '&Eta;': u"\N{GREEK CAPITAL LETTER ETA}",
    '&eta;': u"\N{GREEK SMALL LETTER ETA}",
    '&ETH;': u"\N{LATIN CAPITAL LETTER ETH}",
    '&eth;': u"\N{LATIN SMALL LETTER ETH}",
    '&Euml;': u"\N{LATIN CAPITAL LETTER E WITH DIAERESIS}",
    '&euml;': u"\N{LATIN SMALL LETTER E WITH DIAERESIS}",
    '&euro;': u"\N{EURO SIGN}",
    '&exist;': u"\N{THERE EXISTS}",
    '&fnof;': u"\N{LATIN SMALL LETTER F WITH HOOK}",
    '&forall;': u"\N{FOR ALL}",
    '&frac12;': u"\N{VULGAR FRACTION ONE HALF}",
    '&frac14;': u"\N{VULGAR FRACTION ONE QUARTER}",
    '&frac34;': u"\N{VULGAR FRACTION THREE QUARTERS}",
    '&frasl;': u"\N{FRACTION SLASH}",
    '&Gamma;': u"\N{GREEK CAPITAL LETTER GAMMA}",
    '&gamma;': u"\N{GREEK SMALL LETTER GAMMA}",
    '&ge;': u"\N{GREATER-THAN OR EQUAL TO}",
    '&gt;': '>',
    '&harr;': u"\N{LEFT RIGHT ARROW}",
    '&hArr;': u"\N{LEFT RIGHT DOUBLE ARROW}",
    '&hearts;': u"\N{BLACK HEART SUIT}",
    '&hellip;': u"\N{HORIZONTAL ELLIPSIS}",
    '&Iacute;': u"\N{LATIN CAPITAL LETTER I WITH ACUTE}",
    '&iacute;': u"\N{LATIN SMALL LETTER I WITH ACUTE}",
    '&Icirc;': u"\N{LATIN CAPITAL LETTER I WITH CIRCUMFLEX}",
    '&icirc;': u"\N{LATIN SMALL LETTER I WITH CIRCUMFLEX}",
    '&iexcl;': u"\N{INVERTED EXCLAMATION MARK}",
    '&Igrave;': u"\N{LATIN CAPITAL LETTER I WITH GRAVE}",
    '&igrave;': u"\N{LATIN SMALL LETTER I WITH GRAVE}",
    '&image;': u"\N{BLACK-LETTER CAPITAL I}",
    '&infin;': u"\N{INFINITY}",
    '&int;': u"\N{INTEGRAL}",
    '&Iota;': u"\N{GREEK CAPITAL LETTER IOTA}",
    '&iota;': u"\N{GREEK SMALL LETTER IOTA}",
    '&iquest;': u"\N{INVERTED QUESTION MARK}",
    '&isin;': u"\N{ELEMENT OF}",
    '&Iuml;': u"\N{LATIN CAPITAL LETTER I WITH DIAERESIS}",
    '&iuml;': u"\N{LATIN SMALL LETTER I WITH DIAERESIS}",
    '&Kappa;': u"\N{GREEK CAPITAL LETTER KAPPA}",
    '&kappa;': u"\N{GREEK SMALL LETTER KAPPA}",
    '&Lambda;': u"\N{GREEK CAPITAL LETTER LAMDA}",
    '&lambda;': u"\N{GREEK SMALL LETTER LAMDA}",
    '&lang;': u"\N{LEFT-POINTING ANGLE BRACKET}",
    '&laquo;': u"\N{LEFT-POINTING DOUBLE ANGLE QUOTATION MARK}",
    '&larr;': u"\N{LEFTWARDS ARROW}",
    '&lArr;': u"\N{LEFTWARDS DOUBLE ARROW}",
    '&lceil;': u"\N{LEFT CEILING}",
    '&ldquo;': u"\N{LEFT DOUBLE QUOTATION MARK}",
    '&le;': u"\N{LESS-THAN OR EQUAL TO}",
    '&lfloor;': u"\N{LEFT FLOOR}",
    '&lowast;': u"\N{ASTERISK OPERATOR}",
    '&loz;': u"\N{LOZENGE}",
    '&lrm;': u"\N{LEFT-TO-RIGHT MARK}",
    '&lsaquo;': u"\N{SINGLE LEFT-POINTING ANGLE QUOTATION MARK}",
    '&lsquo;': u"\N{LEFT SINGLE QUOTATION MARK}",
    '&lt;': '<',
    '&macr;': u"\N{MACRON}",
    '&mdash;': "-",
    '&micro;': u"\N{MICRO SIGN}",
    '&middot;': u"\N{MIDDLE DOT}",
    '&minus;': u"\N{MINUS SIGN}",
    '&Mu;': u"\N{GREEK CAPITAL LETTER MU}",
    '&mu;': u"\N{GREEK SMALL LETTER MU}",
    '&nabla;': u"\N{NABLA}",
    '&nbsp;': ' ',
    '&ndash;': "-",
    '&ne;': u"\N{NOT EQUAL TO}",
    '&ni;': u"\N{CONTAINS AS MEMBER}",
    '&notin;': u"\N{NOT AN ELEMENT OF}",
    '&not;': u"\N{NOT SIGN}",
    '&nsub;': u"\N{NOT A SUBSET OF}",
    '&Ntilde;': u"\N{LATIN CAPITAL LETTER N WITH TILDE}",
    '&ntilde;': u"\N{LATIN SMALL LETTER N WITH TILDE}",
    '&Nu;': u"\N{GREEK CAPITAL LETTER NU}",
    '&nu;': u"\N{GREEK SMALL LETTER NU}",
    '&Oacute;': u"\N{LATIN CAPITAL LETTER O WITH ACUTE}",
    '&oacute;': u"\N{LATIN SMALL LETTER O WITH ACUTE}",
    '&Ocirc;': u"\N{LATIN CAPITAL LETTER O WITH CIRCUMFLEX}",
    '&ocirc;': u"\N{LATIN SMALL LETTER O WITH CIRCUMFLEX}",
    '&OElig;': u"\N{LATIN CAPITAL LIGATURE OE}",
    '&oelig;': u"\N{LATIN SMALL LIGATURE OE}",
    '&Ograve;': u"\N{LATIN CAPITAL LETTER O WITH GRAVE}",
    '&ograve;': u"\N{LATIN SMALL LETTER O WITH GRAVE}",
    '&oline;': u"\N{OVERLINE}",
    '&Omega;': u"\N{GREEK CAPITAL LETTER OMEGA}",
    '&omega;': u"\N{GREEK SMALL LETTER OMEGA}",
    '&Omicron;': u"\N{GREEK CAPITAL LETTER OMICRON}",
    '&omicron;': u"\N{GREEK SMALL LETTER OMICRON}",
    '&oplus;': u"\N{CIRCLED PLUS}",
    '&ordf;': u"\N{FEMININE ORDINAL INDICATOR}",
    '&ordm;': u"\N{MASCULINE ORDINAL INDICATOR}",
    '&or;': u"\N{LOGICAL OR}",
    '&Oslash;': u"\N{LATIN CAPITAL LETTER O WITH STROKE}",
    '&oslash;': u"\N{LATIN SMALL LETTER O WITH STROKE}",
    '&Otilde;': u"\N{LATIN CAPITAL LETTER O WITH TILDE}",
    '&otilde;': u"\N{LATIN SMALL LETTER O WITH TILDE}",
    '&otimes;': u"\N{CIRCLED TIMES}",
    '&Ouml;': u"\N{LATIN CAPITAL LETTER O WITH DIAERESIS}",
    '&ouml;': u"\N{LATIN SMALL LETTER O WITH DIAERESIS}",
    '&para;': u"\N{PILCROW SIGN}",
    '&part;': u"\N{PARTIAL DIFFERENTIAL}",
    '&permil;': u"\N{PER MILLE SIGN}",
    '&perp;': u"\N{UP TACK}",
    '&Phi;': u"\N{GREEK CAPITAL LETTER PHI}",
    '&phi;': u"\N{GREEK SMALL LETTER PHI}",
    '&Pi;': u"\N{GREEK CAPITAL LETTER PI}",
    '&pi;': u"\N{GREEK SMALL LETTER PI}",
    '&piv;': u"\N{GREEK PI SYMBOL}",
    '&plusmn;': u"\N{PLUS-MINUS SIGN}",
    '&pound;': u"\N{POUND SIGN}",
    '&Prime;': u"\N{DOUBLE PRIME}",
    '&prime;': u"\N{PRIME}",
    '&prod;': u"\N{N-ARY PRODUCT}",
    '&prop;': u"\N{PROPORTIONAL TO}",
    '&Psi;': u"\N{GREEK CAPITAL LETTER PSI}",
    '&psi;': u"\N{GREEK SMALL LETTER PSI}",
    '&quot;': '"',
    '&radic;': u"\N{SQUARE ROOT}",
    '&rang;': u"\N{RIGHT-POINTING ANGLE BRACKET}",
    '&raquo;': u"\N{RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK}",
    '&rarr;': u"\N{RIGHTWARDS ARROW}",
    '&rArr;': u"\N{RIGHTWARDS DOUBLE ARROW}",
    '&rceil;': u"\N{RIGHT CEILING}",
    '&rdquo;': u"\N{RIGHT DOUBLE QUOTATION MARK}",
    '&real;': u"\N{BLACK-LETTER CAPITAL R}",
    '&reg;': u"\N{REGISTERED SIGN}",
    '&rfloor;': u"\N{RIGHT FLOOR}",
    '&Rho;': u"\N{GREEK CAPITAL LETTER RHO}",
    '&rho;': u"\N{GREEK SMALL LETTER RHO}",
    '&rlm;': u"\N{RIGHT-TO-LEFT MARK}",
    '&rsaquo;': u"\N{SINGLE RIGHT-POINTING ANGLE QUOTATION MARK}",
    '&rsquo;': u"\N{RIGHT SINGLE QUOTATION MARK}",
    '&sbquo;': u"\N{SINGLE LOW-9 QUOTATION MARK}",
    '&Scaron;': u"\N{LATIN CAPITAL LETTER S WITH CARON}",
    '&scaron;': u"\N{LATIN SMALL LETTER S WITH CARON}",
    '&sdot;': u"\N{DOT OPERATOR}",
    '&sect;': u"\N{SECTION SIGN}",
    '&shy;': u"\N{SOFT HYPHEN}",
    '&sigmaf;': u"\N{GREEK SMALL LETTER FINAL SIGMA}",
    '&Sigma;': u"\N{GREEK CAPITAL LETTER SIGMA}",
    '&sigma;': u"\N{GREEK SMALL LETTER SIGMA}",
    '&sim;': u"\N{TILDE OPERATOR}",
    '&spades;': u"\N{BLACK SPADE SUIT}",
    '&sube;': u"\N{SUBSET OF OR EQUAL TO}",
    '&sub;': u"\N{SUBSET OF}",
    '&sum;': u"\N{N-ARY SUMMATION}",
    '&sup1;': u"\N{SUPERSCRIPT ONE}",
    '&sup2;': u"\N{SUPERSCRIPT TWO}",
    '&sup3;': u"\N{SUPERSCRIPT THREE}",
    '&supe;': u"\N{SUPERSET OF OR EQUAL TO}",
    '&sup;': u"\N{SUPERSET OF}",
    '&szlig;': u"\N{LATIN SMALL LETTER SHARP S}",
    '&Tau;': u"\N{GREEK CAPITAL LETTER TAU}",
    '&tau;': u"\N{GREEK SMALL LETTER TAU}",
    '&there4;': u"\N{THEREFORE}",
    '&thetasym;': u"\N{GREEK THETA SYMBOL}",
    '&Theta;': u"\N{GREEK CAPITAL LETTER THETA}",
    '&theta;': u"\N{GREEK SMALL LETTER THETA}",
    '&thinsp;': u"\N{THIN SPACE}",
    '&THORN;': u"\N{LATIN CAPITAL LETTER THORN}",
    '&thorn;': u"\N{LATIN SMALL LETTER THORN}",
    '&tilde;': u"\N{SMALL TILDE}",
    '&times;': u"\N{MULTIPLICATION SIGN}",
    '&trade;': u"\N{TRADE MARK SIGN}",
    '&Uacute;': u"\N{LATIN CAPITAL LETTER U WITH ACUTE}",
    '&uacute;': u"\N{LATIN SMALL LETTER U WITH ACUTE}",
    '&uarr;': u"\N{UPWARDS ARROW}",
    '&uArr;': u"\N{UPWARDS DOUBLE ARROW}",
    '&Ucirc;': u"\N{LATIN CAPITAL LETTER U WITH CIRCUMFLEX}",
    '&ucirc;': u"\N{LATIN SMALL LETTER U WITH CIRCUMFLEX}",
    '&Ugrave;': u"\N{LATIN CAPITAL LETTER U WITH GRAVE}",
    '&ugrave;': u"\N{LATIN SMALL LETTER U WITH GRAVE}",
    '&uml;': u"\N{DIAERESIS}",
    '&upsih;': u"\N{GREEK UPSILON WITH HOOK SYMBOL}",
    '&Upsilon;': u"\N{GREEK CAPITAL LETTER UPSILON}",
    '&upsilon;': u"\N{GREEK SMALL LETTER UPSILON}",
    '&Uuml;': u"\N{LATIN CAPITAL LETTER U WITH DIAERESIS}",
    '&uuml;': u"\N{LATIN SMALL LETTER U WITH DIAERESIS}",
    '&weierp;': u"\N{SCRIPT CAPITAL P}",
    '&Xi;': u"\N{GREEK CAPITAL LETTER XI}",
    '&xi;': u"\N{GREEK SMALL LETTER XI}",
    '&Yacute;': u"\N{LATIN CAPITAL LETTER Y WITH ACUTE}",
    '&yacute;': u"\N{LATIN SMALL LETTER Y WITH ACUTE}",
    '&yen;': u"\N{YEN SIGN}",
    '&Yuml;': u"\N{LATIN CAPITAL LETTER Y WITH DIAERESIS}",
    '&yuml;': u"\N{LATIN SMALL LETTER Y WITH DIAERESIS}",
    '&Zeta;': u"\N{GREEK CAPITAL LETTER ZETA}",
    '&zeta;': u"\N{GREEK SMALL LETTER ZETA}",
    '&zwj;': u"\N{ZERO WIDTH JOINER}",
    '&zwnj;': u"\N{ZERO WIDTH NON-JOINER}",
    }
